### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/work/impl/utils/futures/AbstractFuture;

### ISSUE THREAD

**Issue by smaharjan974** [fluttercommunity/flutter_downloader#223]
I have this error when i update my flutter version to 1.12.13. The version i used before updating the flutter is 1.3.1 and later i updated to 1.4.0 but still getting same error.

[ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/work/impl/utils/futures/AbstractFuture;
E/flutter (19057): 	at androidx.work.impl.WorkManagerImpl.initialize(WorkManagerImpl.java:165)
E/flutter (19057): 	at androidx.work.WorkManager.initialize(WorkManager.java:203)
E/flutter (19057): 	at vn.hunghd.flutterdownloader.FlutterDownloaderInitializer.onCreate(FlutterDownloaderInitializer.java:29)
E/flutter (19057): 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1751)
E/flutter (19057): 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1726)
E/flutter (19057): 	at android.app.ActivityThread.installProvider(ActivityThread.java:6197)
E/flutter (19057): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:5715)
E/flutter (19057): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5636)
E/flutter (19057): 	at android.app.ActivityThread.-wrap2(ActivityThread.java)
E/flutter (19057): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1637)
E/flutter (19057): 	at android.os.Handler.dispatchMessage(Handler.java:105)
E/flutter (19057): 	at android.os.Looper.loop(Looper.java:156)
E/flutter (19057): 	at android.app.ActivityThread.main(ActivityThread.java:6517)
E/flutter (19057): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (19057): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
E/flutter (19057): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
E/flutter (19057): Caused by: java.lang.ClassNotFoundException: androidx.work.impl.utils.futures.AbstractFuture
E/flutter (19057): 	at java.lang.VMClassLoader.findLoadedClass(Native Method)
E/flutter (19057): 	at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
E/flutter (19057): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
E/flutter (19057): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/flutter (19057): 	... 16 more
E/flutter (19057): Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/common/util/concurrent/ListenableFuture;
E/flutter (19057): 	... 16 more
E/flutter (19057): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.common.util.concurrent.ListenableFuture" on path: DexPathList[[zip file "/data/app/siyonkogeetharu.webhousenepal.com.siyonko_geetharu-2/base.apk"],nativeLibraryDirectories=[/data/app/siyonkogeetharu.webhousenepal.com.siyonko_geetharu-2/lib/arm64, /data/app/siyonkogeetharu.webhousenepal.com.siyonko_geetharu-2/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/vendor/lib64, /product/lib64]]
E/flutter (19057): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/flutter (19057): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
E/flutter (19057): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/flutter (19057): 	... 16 more
E/flutter (19057): 
F/flutter (19057): [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(76)] Check failed: CheckException(env).

**Comment by hnvn** [comment]
It looks a problem of AndroidX migration or Gradle dependency conflicts

**Comment by hnvn** [comment]
There's nothing to do in this case. You can try to correct your Gradle settings or have a look at [the example](https://github.com/fluttercommunity/flutter_downloader/tree/master/example) project for suggestions.

**Comment by niusounds** [comment]
In my project, I added these lines to resolve dependency conflicts with Firebase In-App Messaging plugin.

```
configurations.all {
 all*.exclude group: 'com.google.guava', module: 'listenablefuture'
}
```

Recently I updated libraries. App now crashes at start downloading.
I deleted an `all*.exclude group: 'com.google.guava', module: 'listenablefuture'` line. It fixed a problem.

I hope you find it helpful.
